In [12]:
import pandas as pd
import numpy as np
data=[1,2,3,4,5]
df=pd.DataFrame(data)
print(df)
df.shape

   0
0  1
1  2
2  3
3  4
4  5

(5, 1)

In [12]:
import pandas as pd
import numpy as np
df2=pd.read_csv("Iris.csv")
print(df2)
df2.shape
df2.isnull().sum()

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [14]:
x=df2[["Species"]]
print(x)

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [15]:
x=df2.iloc[0:5,0:3]
print(x)

   Id  SepalLengthCm  SepalWidthCm
0   1            5.1           3.5
1   2            4.9           3.0
2   3            4.7           3.2
3   4            4.6           3.1
4   5            5.0           3.6

In [23]:
df2.sort_values(by="Species",ascending=True,inplace=True)
df2.head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa

In [26]:
df2=pd.read_csv("stud_data.csv")
print(df2)
df2.shape
df2.head()
df2.tail()

       Name  Age     City Course  Marks
0     Rahul   21    Delhi  Btech     82
1     Rohan   19      NaN    BCA     85
2    Ranjan   20   Mumbai    MCA     75
3    Ramesh   20   Mumbai    BCA     78
4      Raju   21    Delhi    NaN     83
5    Suresh   22    Delhi    BCA     76
6     Sapna   19  Lucknow    BCA     82
7   Sreshta   21  Lucknow  Btech     68
8      Anju   23    Delhi    MCA     71
9      Rima   22  Lucnkow  Btech     92
10     Rima   22  Lucnkow  Btech     92

       Name  Age     City Course  Marks
6     Sapna   19  Lucknow    BCA     82
7   Sreshta   21  Lucknow  Btech     68
8      Anju   23    Delhi    MCA     71
9      Rima   22  Lucnkow  Btech     92
10     Rima   22  Lucnkow  Btech     92

In [27]:
df2.isnull().sum()

Name      0
Age       0
City      1
Course    1
Marks     0
dtype: int64

In [28]:
df2.describe()

             Age      Marks
count  11.000000  11.000000
mean   20.909091  80.363636
std     1.300350   7.736572
min    19.000000  68.000000
25%    20.000000  75.500000
50%    21.000000  82.000000
75%    22.000000  84.000000
max    23.000000  92.000000

In [39]:
x=df2[["Marks"]]
print(x.sum())

Marks    884
dtype: int64

In [50]:
top_city=df2.groupby("City")["Marks"].sum()
print(top_city)

City
Delhi      312
Lucknow    150
Lucnkow    184
Mumbai     153
Name: Marks, dtype: int64

In [60]:
name = df2.loc[df2["Marks"].idxmax(), "City"]
print(name)

Lucnkow

In [61]:
max_marks = df2["Marks"].max()
result = df2[df2["Marks"] == max_marks]
print(result)

    Name  Age     City Course  Marks
9   Rima   22  Lucnkow  Btech     92
10  Rima   22  Lucnkow  Btech     92

In [106]:
df2=pd.read_csv("messy_data.csv")
print(df2)
df2.shape

      Name   Age  Gender    Income      City Date_of_Joining
0    Alice  25.0  Female   50000.0  New York      2020-06-10
1      Bob   NaN    Male   60000.0       NaN      2021-05-20
2  Charlie  30.0     NaN   80000.0    Boston      2019-08-15
3    David  40.0    Male       NaN  New York      2020-01-30
4      Eva  29.0  Female   72000.0   Chicago             NaN
5    Alice  25.0  Female   50000.0  New York      2020-06-10
6    Frank  38.0    Male  900000.0    Boston      2018-03-10

(7, 6)

In [63]:
df2.isnull()

    Name    Age  Gender  Income   City  Date_of_Joining
0  False  False   False   False  False            False
1  False   True   False   False   True            False
2  False  False    True   False  False            False
3  False  False   False    True  False            False
4  False  False   False   False  False             True
5  False  False   False   False  False            False
6  False  False   False   False  False            False

In [107]:
df2.isnull().sum()

Name               0
Age                1
Gender             1
Income             1
City               1
Date_of_Joining    1
dtype: int64

In [65]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             7 non-null      object
 1   Age              6 non-null      float64
 2   Gender           6 non-null      object
 3   Income           6 non-null      float64
 4   City             6 non-null      object
 5   Date_of_Joining  6 non-null      object
dtypes: float64(2), object(4)
memory usage: 468.0+ bytes

In [71]:
#Fill missing values

df2['Age']=df2['Age'].fillna(df2['Age'].median())
df2['Income']=df2['Income'].fillna(df2['Income'].median())
df2['Gender']=df2['Gender'].fillna(df2['Gender'].mode()[0])
df2['City']=df2['City'].fillna(df2['City'].mode()[0])
df2['Date_of_Joining']=df2['Date_of_Joining'].fillna('2022-01-01')
df2.isnull().sum()

Name               0
Age                0
Gender             0
Income             0
City               0
Date_of_Joining    0
dtype: int64

In [80]:
#Check Duplicate Values
df2.duplicated().sum()

np.int64(0)

In [81]:
#Drop Duplicates
df2.drop_duplicates(inplace=True)
df2.duplicated().sum()

np.int64(0)

In [83]:
df2.dtypes

Name                object
Age                float64
Gender              object
Income             float64
City                object
Date_of_Joining     object
dtype: object

In [108]:
#Converting Data_Types
df2['Date_of_Joining']=pd.to_datetime(df2['Date_of_Joining'])
df2['Gender']=df2['Gender'].astype('category')
df2.dtypes

Name                       object
Age                       float64
Gender                   category
Income                    float64
City                       object
Date_of_Joining    datetime64[ns]
dtype: object

In [90]:
q1=df2['Income'].quantile(0.25)
print(q1)
q3=df2['Income'].quantile(0.75)
print(q3)
iqr=

61500.0
78000.0
16500.0

In [116]:
#Removing Outliers
df2=df2[(df2['Income']>=q1-1.5*iqr)&(df2['Income']>=q3+1.5*iqr)]
print(df2)
df2.shape
print(df2.columns)

    Name   Age Gender    Income Date_of_Joining
6  Frank  38.0   Male  900000.0      2018-03-10
Index(['Name', 'Age', 'Gender', 'Income', 'Date_of_Joining'], dtype='object')

In [117]:
df2=pd.get_dummies(df2,columns=['Name'],drop_first=True)
print(df2)

    Age Gender    Income Date_of_Joining
6  38.0   Male  900000.0      2018-03-10

In [ ]:
import sick